### ISSUE TITLE
generateNewAddress's customerRefId parameter is character sensitive

### ISSUE THREAD

**Issue by ehamery** [fireblocks/fireblocks-sdk-js#93]
**Describe the bug**
Calling these works fine:
```
fireblocks.generateNewAddress('42', 'BTC_TEST', '104', '104');
fireblocks.generateNewAddress('42', 'BTC_TEST', 'user#104', '104');
```
Calling this produces an error:
```
fireblocks.generateNewAddress('42', 'BTC_TEST', 'user#104', 'user#104');
```
```
2022-05-23T03:55:50.762Z error - unhandledRejection error: Request failed with status code 400
Error: Request failed with status code 400
    at createError (/xxx/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/xxx/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/xxx/node_modules/axios/lib/adapters/http.js:293:11)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
```
**To Reproduce**
See above

**Expected behavior**
Expecting to be able to provide special characters in `customerRefId` when calling `generateNewAddress()`

**Screenshots**
Not applicable

**Version:**
 - `fireblocks-sdk` version: ?
 - npm version: 2.1.0
 - node version: v14.18.1

**Additional context**
None

**Comment by ehamery** [comment]
Hi, any update/comment on this?

**Comment by yarinvak** [comment]
Hey @ehamery 

This is the intended behavior, we don't allow special characters in `customerRefId`.

If you have any questions regarding this, please contact Fireblocks Support Team.

**Comment by ehamery** [comment]
Is that documented anywhere?
What is the exactly list of characters allowed?
The error does not say anything about the issue and it could be easily checked before the request gets sent.
You work at Fireblocks, can't you get them involved instead of just closing the ticket...??
